=pod

=encoding utf8

=head1 NAME

Device::GBA - Perl Interface to the Gameboy Advance
=head1 SYNOPSIS

=head1 VERSION

version 0.001

    use Device::GBA;

    my $gba = Device::GBA->new(buspirate => '/dev/ttyUSB0') or die "No such device!\n";
    $gba->upload('helloworld.gba');


=head1 METHODS AND ARGUMENTS

=over 4

=item new()

Opens specified device and returns the corresponding object reference. Returns undef
if an attempt to open the device has failed. Accepts following parameters:

=over 4

=item B<buspirate>

COM port or handle of the BusPirate connected to the Gameboy Advance.

=item B<spi>

L<Device::BusPirate::Mode::SPI> instance.

=item B<verbose>

if true, methods on this instance will narrate what they're doing. Default is C<0>.

=back

=item upload

    $gba->upload($firmware_file)

Reads in I<$firmware_file> and uploads it to the Gameboy Advance.

=item spi_writeread

    $miso = $gba->spi_writeread($mosi)

reads and writes 32 bit from the SPI bus.

=item crc

    $c = Device::GBA::crc($w, [$c = 0x0000c387])

Calculates CRC for word C<$w> and CRC C<$c> according to the algrithm used by the GBA multiboot protocol.

=back

=head1 GIT REPOSITORY

L<http://github.com/athreef/Device-GBA>

=head1 SEE ALSO

L<gba> -- The command line utility

=head1 AUTHOR

Ahmad Fatoum C<< <athreef@cpan.org> >>, L<http://a3f.at>

Based on The uploader written by Ken Kaarvik.

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2018 Ahmad Fatoum

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
